version: "3.7"
services:
  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "127.0.0.1:50021:50021"
    tty: true
  node:
    build: .
    init: true
    restart: always
    environment:
      - VOICE_HOST=voicevox_engine
    ports:
      - "127.0.0.1:3180:3000"
    volumes:
      - ./wav:/app/wav

